export * from './Coordinates.model.js'
export * from './Course.model.js'
export * from './Schedule.model.js'
export * from './ScheduleBlock.model.js'
export * from './Spaces/SpaceBase.model.js'
export * from './Spaces/Office.model.js'
export * from './Spaces/Classroom.model.js'
export * from './Spaces/Laboratory.model.js'